version: '3.8'

services:
  # Frontend Service (Vite/React)
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: maison-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://calendar-backend:8000
    volumes:
      - ./:/app
      - /app/node_modules
    restart: unless-stopped

  # Calendar Backend Service (from separate repo)
  calendar-backend:
    build:
      context: ../MaiSON-backend/MaiSON-cal
      dockerfile: Dockerfile
    container_name: maison-calendar-backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - PORT=8000
    restart: unless-stopped
    env_file:
      - .env

volumes:
  postgres_data:
    driver: local